use_frameworks!

target 'Frankfurter_Example' do
  pod 'Frankfurter', :path => '../'

  target 'Frankfurter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
