platform :ios, '10.0'
use_frameworks!

target 'Frankfurter_Example' do
  pod 'Alamofire', '~> 4.8.2'
  pod 'Frankfurter', :path => '../'
  

  target 'Frankfurter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
